<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="12" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-20T07:43:01 IST" name="ActitimeTests" finished-at="2022-05-20T07:43:55 IST" duration-ms="54500">
    <groups>
    </groups>
    <test started-at="2022-05-20T07:43:01 IST" name="Projects" finished-at="2022-05-20T07:43:55 IST" duration-ms="54500">
      <class name="com.actitime.tests.Login">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:03 IST" name="beforeClass" finished-at="2022-05-20T07:43:03 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:03 IST" name="launchApplication" finished-at="2022-05-20T07:43:20 IST" duration-ms="17318" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login_001()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:20 IST" name="login_001" finished-at="2022-05-20T07:43:26 IST" duration-ms="6282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_001 -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:27 IST" name="closeBrowser" finished-at="2022-05-20T07:43:29 IST" duration-ms="1537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:29 IST" name="launchApplication" finished-at="2022-05-20T07:43:48 IST" duration-ms="19047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="login_002()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:48 IST" name="login_002" finished-at="2022-05-20T07:43:54 IST" duration-ms="6034" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not login to ActiTime application.. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not login to ActiTime application.. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertFalse(Assert.java:78)
at com.actitime.tests.Login.login_002(Login.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_002 -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:54 IST" name="closeBrowser" finished-at="2022-05-20T07:43:55 IST" duration-ms="1105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.actitime.tests.Login@6e46d9f4]" started-at="2022-05-20T07:43:55 IST" name="afterClass" finished-at="2022-05-20T07:43:55 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.actitime.tests.Login -->
      <class name="com.actitime.tests.AutoITAndRobotClass_May16">
        <test-method is-config="true" signature="beoreTest()[pri:0, instance:com.actitime.tests.AutoITAndRobotClass_May16@7bf9b098]" started-at="2022-05-20T07:43:02 IST" name="beoreTest" finished-at="2022-05-20T07:43:03 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.actitime.tests.AutoITAndRobotClass_May16@7bf9b098]" started-at="2022-05-20T07:43:55 IST" name="afterTest" finished-at="2022-05-20T07:43:55 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.actitime.tests.AutoITAndRobotClass_May16 -->
    </test> <!-- Projects -->
  </suite> <!-- ActitimeTests -->
</testng-results>
